Repository celtrix-os/Celtrix, pull requests merged in 2025-10, with the labels that each got.

#85 Format the current readme file
  README.md
Labels: hacktoberfest

#74 Added user schema with password validation
  templates/mern+tailwind+auth/javascript/server/models/User.js
Labels: hacktoberfest

#116 Mern smd
  templates/mern/javascript/client/.gitignore
  templates/mern/javascript/client/README.md
  templates/mern/javascript/client/eslint.config.js
  templates/mern/javascript/client/index.html
  templates/mern/javascript/client/package-lock.json
  templates/mern/javascript/client/package.json
  templates/mern/javascript/client/public/vite.svg
  templates/mern/javascript/client/src/App.css
  templates/mern/javascript/client/src/App.jsx
  templates/mern/javascript/client/src/assets/react.svg
  templates/mern/javascript/client/src/index.css
  templates/mern/javascript/client/src/main.jsx
  templates/mern/javascript/client/vite.config.js
  templates/mern/javascript/server/package-lock.json
  templates/mern/javascript/server/package.json
  templates/mern/javascript/server/routes/.gitkeep
  templates/mern/server/.env.example
  templates/mern/server/.gitignore
  templates/mern/server/controllers/.gitkeep
  templates/mern/server/models/.gitkeep
  templates/mern/server/routes/.gitkeep
  templates/mern/server/server.js
  templates/mern/typescript/client/.gitignore
  templates/mern/typescript/client/README.md
  templates/mern/typescript/client/eslint.config.js
  templates/mern/typescript/client/index.html
  templates/mern/typescript/client/package-lock.json
  templates/mern/typescript/client/package.json
  templates/mern/typescript/client/public/vite.svg
  templates/mern/typescript/client/src/App.css
  templates/mern/typescript/client/src/App.tsx
  templates/mern/typescript/client/src/assets/react.svg
  templates/mern/typescript/client/src/index.css
  templates/mern/typescript/client/src/main.tsx
  templates/mern/typescript/client/src/vite-env.d.ts
  templates/mern/typescript/client/tsconfig.app.json
  templates/mern/typescript/client/tsconfig.json
  templates/mern/typescript/client/tsconfig.node.json
  templates/mern/typescript/client/vite.config.ts
  templates/mern/typescript/server/.env.example
  templates/mern/typescript/server/controllers/.gitkeep
  templates/mern/typescript/server/models/.gitkeep
  templates/mern/typescript/server/package-lock.json
  templates/mern/typescript/server/package.json
  templates/mern/typescript/server/routes/.gitkeep
  templates/mern/typescript/server/server.js
  utils/installer.js
  utils/project.js
  utils/templateManager.js
Labels: hacktoberfest

#119 modified the bot
  scripts/check-duplicates.js
Labels: hacktoberfest

#121 Updated the workflows version of node , actions , checkout and fixed the syntax of if
  .github/workflows/api-validation.yml
  .github/workflows/database-operations.yml
  .github/workflows/duplicate-issue.yml
Labels: hacktoberfest

#136 Create FileSystemUtility for Ts Backend
  templates/mern/Ts-Backend/package.json
  templates/mern/Ts-Backend/pnpm-lock.yaml
  templates/mern/Ts-Backend/server.ts
  templates/mern/Ts-Backend/src/__test__/index.test.ts
  templates/mern/Ts-Backend/src/api/user/v1/user.controller.ts
  templates/mern/Ts-Backend/src/app.ts
  templates/mern/Ts-Backend/src/config/db.config.ts
  templates/mern/Ts-Backend/src/config/socket.config.ts
  templates/mern/Ts-Backend/src/constant/env.constant.ts
  templates/mern/Ts-Backend/src/type/FileSystem.type.ts
  templates/mern/Ts-Backend/src/utils/FileSystem.utility.ts
  templates/mern/Ts-Backend/src/utils/SendResponse.utils.ts
  templates/mern/Ts-Backend/src/validator/env.validator.ts
  templates/mern/Ts-Backend/tsconfig.json
Labels: hacktoberfest-accepted

#81 added contributors section
  README.md
Labels: hacktoberfest

#101 docs: add expanded FAQ section to README (issue #95)
  README.md
Labels: hacktoberfest

#141 docs: move FAQs to separate FAQ.md and link it in README
  FAQ.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
